defmodule MyXDR do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr
  """

  comment ~S"""
  XDR Source Code::

      typedef int Error;
  """

  define_type("Error", Int)

  comment ~S"""
  XDR Source Code::

      typedef int Multi;
  """

  define_type("Multi", Int)

  comment ~S"""
  XDR Source Code::

      enum UnionKey {
        ERROR,
        MULTI
      };
  """


  comment ~S"""
  XDR Source Code::

      union MyUnion switch (UnionKey type)
      {
          case ERROR:
              Error error;
          case MULTI:
              Multi things<>;
      
      
      };
  """

  define_type("MyUnion", Union,
    switch_type: "UnionKey",
    switch_name: :TYPE,
    switches: [
      {:ERROR, :ERROR},
      {:MULTI, :THINGS},
    ],
    arms: [
      ERROR: "Error",
      THINGS: build_type(VariableArray, max_length: 2147483647, type: "Multi"),
    ]
  )

  comment ~S"""
  XDR Source Code::

      union IntUnion switch (int type)
      {
          case 0:
              Error error;
          case 1:
              Multi things<>;
      
      };
  """

  define_type("IntUnion", Union,
    switch_type: build_type(Int),
    switch_name: :TYPE,
    switches: [
      {0, :ERROR},
      {1, :THINGS},
    ],
    arms: [
      ERROR: "Error",
      THINGS: build_type(VariableArray, max_length: 2147483647, type: "Multi"),
    ]
  )

  comment ~S"""
  XDR Source Code::

      typedef IntUnion IntUnion2;
  """

  define_type("IntUnion2", "IntUnion")

end
