defmodule MyXDR do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: exdr at https://hex.pm/packages/exdr
  """

  use XDR.Base

  comment ~S"""
  === xdr source ============================================================

      const BASE_VALUE = 1;

  ===========================================================================
  """
  define_type("BASE_VALUE", Const, 1);

  comment ~S"""
  === xdr source ============================================================

      enum MyEnum {
          MEMBER_A = 0,
          MEMBER_B = 1,
                      
          MEMBER_C = 2,
            
          MEMBER_D = 3
      };

  ===========================================================================
  """
  define_type("MyEnum", Enum,
    member_a: 0,
    member_b: 1,
    member_c: 2,
    member_d: 3
  )

  comment ~S"""
  === xdr source ============================================================

      struct MyStruct {
          int field1;
          MyEnum field2;
                      
          unsigned int field3;
            
      };

  ===========================================================================
  """
  define_type("MyStruct", Struct,
    field1: build_type(Int),
    field2: "MyEnum",
    field3: build_type(UnsignedInt)
  )

  comment ~S"""
  === xdr source ============================================================

      struct ConditionalStruct {
          int data;
      };

  ===========================================================================
  """
  define_type("ConditionalStruct", Struct,
    data: build_type(Int)
  )

  comment ~S"""
  === xdr source ============================================================

      struct VariantStruct {
          int newField;
      };

  ===========================================================================
  """
  define_type("VariantStruct", Struct,
    new_field: build_type(Int)
  )

  comment ~S"""
  === xdr source ============================================================

      struct VariantStruct {
          unsigned int oldField;
      };

  ===========================================================================
  """
  define_type("VariantStruct", Struct,
    old_field: build_type(UnsignedInt)
  )

  comment ~S"""
  === xdr source ============================================================

      enum UnionType {
          UNION_A = 0,
          UNION_B = 1,
                      
          UNION_C = 2,
            
          UNION_D = 3
      };

  ===========================================================================
  """
  define_type("UnionType", Enum,
    union_a: 0,
    union_b: 1,
    union_c: 2,
    union_d: 3
  )

  comment ~S"""
  === xdr source ============================================================

      union MyUnion switch (UnionType type) {
          case UNION_A:
              int armA;
          case UNION_B:
              unsigned int armB;
                      
          case UNION_C:
              unsigned hyper armC;
            
          case UNION_D:
              void;
      };

  ===========================================================================
  """
  define_type("MyUnion", Union,
    switch_type: "UnionType",
    switch_name: :type,
    switches: [
      {:union_a, :arm_a},
      {:union_b, :arm_b},
      {:union_c, :arm_c},
      {:union_d, XDR.Type.Void},
    ],
    arms: [
      arm_a: build_type(Int),
      arm_b: build_type(UnsignedInt),
      arm_c: build_type(UnsignedHyperInt),
    ]
  )

end
