defmodule MyXDR.MyUnionOne do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `MyUnionOne` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.{
    Int
  }

  @struct_spec XDR.Struct.new(
    some_int: Int
  )

  @type type_some_int :: Int.t()

  @type t :: %__MODULE__{some_int: type_some_int()}

  defstruct [:some_int]

  @spec new(some_int :: type_some_int()) :: t()
  def new(
    %Int{} = some_int
  ),
  do: %__MODULE__{some_int: some_int}

  @impl true
  def encode_xdr(%__MODULE__{some_int: some_int}) do
    [some_int: some_int]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{some_int: some_int}) do
    [some_int: some_int]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [some_int: some_int]}, rest}} ->
        {:ok, {new(some_int), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [some_int: some_int]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(some_int), rest}
  end
end
