defmodule MyXDR.Two do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `Two` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.{Int, Foo} 

  @struct_spec XDR.Struct.new(
    someInt: Int,
    foo: Foo
  )

  @type someInt :: Int.t()
  @type foo :: Foo.t()

  @type t :: %__MODULE__{someInt: someInt(), foo: foo()}

  defstruct [:someInt, :foo]

  @spec new(someInt :: someInt(), foo :: foo()) :: t()

  def new(
    %Int{} = someInt,
    %Foo{} = foo
  ),
  do: %__MODULE__{someInt: someInt, foo: foo}

  @impl true
  def encode_xdr(%__MODULE__{someInt: someInt, foo: foo}) do 
    [someInt: someInt, foo: foo]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end 

  @impl true
  def encode_xdr!(%__MODULE__{someInt: someInt, foo: foo}) do 
    [someInt: someInt, foo: foo]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end 

  @impl true 
  def decode_xdr(bytes, struct \\ @struct_spec) 

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [someInt: someInt, foo: foo]}, rest}} -> 
        {:ok, {new(someInt, foo), rest}}
      error -> error
    end
  end 

  @impl true 
  def decode_xdr!(bytes, struct \\ @struct_spec) 

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [someInt: someInt, foo: foo]}, rest} = 
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(someInt, foo), rest}
  end
end
