defmodule MyXDR.MyStruct do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `MyStruct` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.{Int, Int64, FixedOpaque10, String, String100} 

  @struct_spec XDR.Struct.new(
    someInt: Int,
    aBigInt: Int64,
    someOpaque: FixedOpaque10,
    someString: String,
    maxString: String100
  )

  @type someInt :: Int.t()
  @type aBigInt :: Int64.t()
  @type someOpaque :: FixedOpaque10.t()
  @type someString :: String.t()
  @type maxString :: String100.t()

  @type t :: %__MODULE__{someInt: someInt(), aBigInt: aBigInt(), someOpaque: someOpaque(), someString: someString(), maxString: maxString()}

  defstruct [:someInt, :aBigInt, :someOpaque, :someString, :maxString]

  @spec new(someInt :: someInt(), aBigInt :: aBigInt(), someOpaque :: someOpaque(), someString :: someString(), maxString :: maxString()) :: t()

  def new(
    %Int{} = someInt,
    %Int64{} = aBigInt,
    %FixedOpaque10{} = someOpaque,
    %String{} = someString,
    %String100{} = maxString
  ),
  do: %__MODULE__{someInt: someInt, aBigInt: aBigInt, someOpaque: someOpaque, someString: someString, maxString: maxString}

  @impl true
  def encode_xdr(%__MODULE__{someInt: someInt, aBigInt: aBigInt, someOpaque: someOpaque, someString: someString, maxString: maxString}) do 
    [someInt: someInt, aBigInt: aBigInt, someOpaque: someOpaque, someString: someString, maxString: maxString]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end 

  @impl true
  def encode_xdr!(%__MODULE__{someInt: someInt, aBigInt: aBigInt, someOpaque: someOpaque, someString: someString, maxString: maxString}) do 
    [someInt: someInt, aBigInt: aBigInt, someOpaque: someOpaque, someString: someString, maxString: maxString]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end 

  @impl true 
  def decode_xdr(bytes, struct \\ @struct_spec) 

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [someInt: someInt, aBigInt: aBigInt, someOpaque: someOpaque, someString: someString, maxString: maxString]}, rest}} -> 
        {:ok, {new(someInt, aBigInt, someOpaque, someString, maxString), rest}}
      error -> error
    end
  end 

  @impl true 
  def decode_xdr!(bytes, struct \\ @struct_spec) 

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [someInt: someInt, aBigInt: aBigInt, someOpaque: someOpaque, someString: someString, maxString: maxString]}, rest} = 
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(someInt, aBigInt, someOpaque, someString, maxString), rest}
  end
end
