defmodule MyXDR do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr
  """

  comment ~S"""
  XDR Source Code::

      typedef hyper int64;
  """

  define_type("Int64", HyperInt)

  comment ~S"""
  XDR Source Code::

      struct MyStruct
      {
          int    someInt;
          int64  aBigInt;
          opaque someOpaque[10];
          string someString<>;
          string maxString<100>;
      };
  """


end
