// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;


import java.io.IOException;


// === xdr source ============================================================

//  enum UnionKey {
//    ONE = 1,
//    TWO = 2,
//    OFFER = 3
//  };

//  ===========================================================================
public enum UnionKey implements XdrElement {
  ONE(1),
  TWO(2),
  OFFER(3),
  ;
  private int mValue;

  UnionKey(int value) {
      mValue = value;
  }

  public int getValue() {
      return mValue;
  }

  public static UnionKey decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 1: return ONE;
      case 2: return TWO;
      case 3: return OFFER;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, UnionKey value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
}
