defmodule MyXDR do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr
  """

  comment ~S"""
  XDR Source Code::

      typedef int Arr[2];
  """


  comment ~S"""
  XDR Source Code::

      struct HasOptions
      {
        int* firstOption;
        int *secondOption;
        Arr *thirdOption;
      };
  """


end
