defmodule MyXDR.OptionalInt do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptionalInt` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.Int

  @optional_spec XDR.Optional.new(Int)

  @type int :: Int.t() | nil

  @type t :: %__MODULE__{int: int()}

  defstruct [:int]

  @spec new(int :: int()) :: t()
  def new(int \\ nil), do: %__MODULE__{int: int}

  @impl true
  def encode_xdr(%__MODULE__{int: int}) do
    int
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{int: int}) do
    int
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: int}, rest}} -> {:ok, {new(int), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    case XDR.Optional.decode_xdr!(bytes, optional_spec) do
      {%XDR.Optional{type: int}, rest} -> {new(int), rest}
      {nil, rest} -> {new(), rest}
    end
  end

end
