// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;


import java.io.IOException;


// === xdr source ============================================================

//  enum Color {
//      RED=0,  
//      GREEN=1,  
//      BLUE=2  
//  };

//  ===========================================================================
public enum Color implements XdrElement {
  RED(0),
  GREEN(1),
  BLUE(2),
  ;
  private int mValue;

  Color(int value) {
      mValue = value;
  }

  public int getValue() {
      return mValue;
  }

  public static Color decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0: return RED;
      case 1: return GREEN;
      case 2: return BLUE;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, Color value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
}
