// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;


import java.io.IOException;


// === xdr source ============================================================

//  enum Color2 {
//      RED2=RED,  
//      GREEN2=1,  
//      BLUE2=2  
//  };

//  ===========================================================================
public enum Color2 implements XdrElement {
  RED2(0),
  GREEN2(1),
  BLUE2(2),
  ;
  private int mValue;

  Color2(int value) {
      mValue = value;
  }

  public int getValue() {
      return mValue;
  }

  public static Color2 decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0: return RED2;
      case 1: return GREEN2;
      case 2: return BLUE2;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, Color2 value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
}
