// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;


import java.io.IOException;


// === xdr source ============================================================

//  enum Color3 {
//      RED3=RED,  
//      GREEN3=1000,  
//      BLUE3=2000  
//  };

//  ===========================================================================
public enum Color3 implements XdrElement {
  RED3(0),
  GREEN3(1000),
  BLUE3(2000),
  ;
  private int mValue;

  Color3(int value) {
      mValue = value;
  }

  public int getValue() {
      return mValue;
  }

  public static Color3 decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0: return RED3;
      case 1000: return GREEN3;
      case 2000: return BLUE3;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, Color3 value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
}
