defmodule MyXDR do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: exdr at https://hex.pm/packages/exdr
  """

  use XDR.Base

  comment ~S"""
  === xdr source ============================================================

      enum AccountFlags
      { // masks for each flag
          AUTH_REQUIRED_FLAG = 0x1
      };

  ===========================================================================
  """
  define_type("AccountFlags", Enum,
    auth_required_flag: 1
  )

end
