defmodule MyXDR do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr
  """

  comment ~S"""
  XDR Source Code::

      enum AccountFlags
      { // masks for each flag
          AUTH_REQUIRED_FLAG = 0x1
      };
  """


end
