// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;


import java.io.IOException;

import com.google.common.base.Objects;
import java.util.Arrays;

// === xdr source ============================================================

//  union IntUnion3 switch (int type)
//  {
//      case 0:
//          Error error;
//      case 1000:
//          Multi things<>;
//  
//  };

//  ===========================================================================
public class IntUnion3 implements XdrElement {
  public IntUnion3 () {}
  Integer type;
  public Integer getDiscriminant() {
    return this.type;
  }
  public void setDiscriminant(Integer value) {
    this.type = value;
  }
  private Error error;
  public Error getError() {
    return this.error;
  }
  public void setError(Error value) {
    this.error = value;
  }
  private Multi[] things;
  public Multi[] getThings() {
    return this.things;
  }
  public void setThings(Multi[] value) {
    this.things = value;
  }

  public static final class Builder {
    private Integer discriminant;
    private Error error;
    private Multi[] things;

    public Builder discriminant(Integer discriminant) {
      this.discriminant = discriminant;
      return this;
    }

    public Builder error(Error error) {
      this.error = error;
      return this;
    }

    public Builder things(Multi[] things) {
      this.things = things;
      return this;
    }

    public IntUnion3 build() {
      IntUnion3 val = new IntUnion3();
      val.setDiscriminant(discriminant);
      val.setError(error);
      val.setThings(things);
      return val;
    }
  }

  public static void encode(XdrDataOutputStream stream, IntUnion3 encodedIntUnion3) throws IOException {
  //Xdrgen::AST::Typespecs::Int
  //Integer
  stream.writeInt(encodedIntUnion3.getDiscriminant().intValue());
  switch (encodedIntUnion3.getDiscriminant()) {
  case 0:
  Error.encode(stream, encodedIntUnion3.error);
  break;
  case 1000:
  int thingssize = encodedIntUnion3.getThings().length;
  stream.writeInt(thingssize);
  for (int i = 0; i < thingssize; i++) {
    Multi.encode(stream, encodedIntUnion3.things[i]);
  }
  break;
  }
  }
  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
  public static IntUnion3 decode(XdrDataInputStream stream) throws IOException {
  IntUnion3 decodedIntUnion3 = new IntUnion3();
  Integer discriminant = stream.readInt();
  decodedIntUnion3.setDiscriminant(discriminant);
  switch (decodedIntUnion3.getDiscriminant()) {
  case 0:
  decodedIntUnion3.error = Error.decode(stream);
  break;
  case 1000:
  int thingssize = stream.readInt();
  decodedIntUnion3.things = new Multi[thingssize];
  for (int i = 0; i < thingssize; i++) {
    decodedIntUnion3.things[i] = Multi.decode(stream);
  }
  break;
  }
    return decodedIntUnion3;
  }
  @Override
  public int hashCode() {
    return Objects.hashCode(this.error, Arrays.hashCode(this.things), this.type);
  }
  @Override
  public boolean equals(Object object) {
    if (!(object instanceof IntUnion3)) {
      return false;
    }

    IntUnion3 other = (IntUnion3) object;
    return Objects.equal(this.error, other.error) && Arrays.equals(this.things, other.things) && Objects.equal(this.type, other.type);
  }
}
