defmodule MyXDR.HasStuff do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `HasStuff` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.{
    LotsOfMyStructs
  } 

  @struct_spec XDR.Struct.new(
    data: LotsOfMyStructs
  )

  @type data :: LotsOfMyStructs.t()

  @type t :: %__MODULE__{data: data()}

  defstruct [:data]

  @spec new(data :: data()) :: t()
  def new(
    %LotsOfMyStructs{} = data
  ),
  do: %__MODULE__{data: data}

  @impl true
  def encode_xdr(%__MODULE__{data: data}) do
    [data: data]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{data: data}) do
    [data: data]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [data: data]}, rest}} ->
        {:ok, {new(data), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [data: data]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(data), rest}
  end
end
