defmodule MyXDR do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr
  """

  comment ~S"""
  XDR Source Code::

      typedef opaque uint512[64];
  """


  comment ~S"""
  XDR Source Code::

      typedef opaque uint513<64>;
  """


  comment ~S"""
  XDR Source Code::

      typedef opaque uint514<>;
  """


  comment ~S"""
  XDR Source Code::

      typedef string str<64>;
  """


  comment ~S"""
  XDR Source Code::

      typedef string str2<>;
  """


  comment ~S"""
  XDR Source Code::

      typedef opaque Hash[32];
  """


  comment ~S"""
  XDR Source Code::

      typedef Hash Hashes1[12];
  """


  comment ~S"""
  XDR Source Code::

      typedef Hash Hashes2<12>;
  """


  comment ~S"""
  XDR Source Code::

      typedef Hash Hashes3<>;
  """


  comment ~S"""
  XDR Source Code::

      typedef Hash *optHash1;
  """


  comment ~S"""
  XDR Source Code::

      typedef Hash* optHash2;
  """


  comment ~S"""
  XDR Source Code::

      typedef int             int1;
  """


  comment ~S"""
  XDR Source Code::

      typedef hyper           int2;
  """


  comment ~S"""
  XDR Source Code::

      typedef unsigned int    int3;
  """


  comment ~S"""
  XDR Source Code::

      typedef unsigned hyper  int4;
  """


  comment ~S"""
  XDR Source Code::

      struct MyStruct
      {
          uint512 field1;
          optHash1 field2;
          int1 field3;
          unsigned int field4;
          float field5;
          double field6;
          bool field7;
      };
  """


  comment ~S"""
  XDR Source Code::

      struct LotsOfMyStructs
      {
          MyStruct members<>;
      };
  """


  comment ~S"""
  XDR Source Code::

      struct HasStuff
      {
        LotsOfMyStructs data;
      };
  """


  comment ~S"""
  XDR Source Code::

      enum Color {
        RED,
        BLUE = 5,
        GREEN
      };
  """


  comment ~S"""
  XDR Source Code::

      const FOO = 1244;
  """

  define_type("FOO", Const, 1244);

  comment ~S"""
  XDR Source Code::

      const BAR = FOO;
  """

  define_type("BAR", Const, FOO);

  comment ~S"""
  XDR Source Code::

      enum {
          BLAH_1,
          BLAH_2
        }
  """


  comment ~S"""
  XDR Source Code::

      struct {
          int blah;
        }
  """


  comment ~S"""
  XDR Source Code::

      union switch (Color color) {
          case RED:
            void;
          default:
            int blah2;
        }
  """


  comment ~S"""
  XDR Source Code::

      struct Nester
      {
        enum {
          BLAH_1,
          BLAH_2
        } nestedEnum;
      
        struct {
          int blah;
        } nestedStruct;
      
        union switch (Color color) {
          case RED:
            void;
          default:
            int blah2;
        } nestedUnion;
      
      
      };
  """


end
