defmodule MyXDR.NesterNestedStruct do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `NesterNestedStruct` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.{
    Int
  }

  @struct_spec XDR.Struct.new(
    blah: Int
  )

  @type blah_type :: Int.t()

  @type t :: %__MODULE__{blah: blah_type()}

  defstruct [:blah]

  @spec new(blah :: blah_type()) :: t()
  def new(
    %Int{} = blah
  ),
  do: %__MODULE__{blah: blah}

  @impl true
  def encode_xdr(%__MODULE__{blah: blah}) do
    [blah: blah]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{blah: blah}) do
    [blah: blah]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [blah: blah]}, rest}} ->
        {:ok, {new(blah), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [blah: blah]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(blah), rest}
  end
end
