module Xdrgen
  module Generators
    class Elixir < Xdrgen::Generators::Base
      MAX_INT = (2**31) - 1

      def generate
        path = "#{@namespace}_generated.ex"
        out = @output.open(path)

        render_define_block(out) do
          out.indent() do
            render_definitions(out, @top)
          end
        end
      end

      private
      def render_definitions(out, node)
        node.definitions.each{|n| render_definition out, n }
        node.namespaces.each{|n| render_definitions out, n }
      end

      def render_nested_definitions(out, defn)
        return unless defn.respond_to? :nested_definitions
        defn.nested_definitions.each{|ndefn| render_definition out, ndefn}
      end

      def render_definition(out, defn)
        render_nested_definitions(out, defn)
        render_source_comment(out, defn)

        case defn
        when AST::Definitions::Struct ;
          render_struct out, defn
        when AST::Definitions::Enum ;
          render_enum defn
        when AST::Definitions::Union ;
          render_union out, defn
        when AST::Definitions::Typedef ;
          render_typedef out, defn
        when AST::Definitions::Const ;
          render_const out, defn
        end

        out.break
      end

      def render_source_comment(out, defn)
        return if defn.is_a?(AST::Definitions::Namespace)

        out.puts <<-EOS.strip_heredoc
          comment ~S"""
          XDR Source Code::\n
        EOS

        out.puts "    " + defn.text_value.split("\n").join("\n    ")

        out.puts <<-EOS.strip_heredoc
          """\n
        EOS
      end

      def render_moduledoc(out)
        out.puts <<-EOS.strip_heredoc
          @moduledoc """
          Automatically generated by xdrgen
          DO NOT EDIT or your changes may be overwritten

          Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr
          """
        EOS
        out.break
      end

      def render_moduledoc_enum_type(out, type)
        out.puts <<-EOS.strip_heredoc
          @moduledoc """
          Automatically generated by xdrgen
          DO NOT EDIT or your changes may be overwritten

          Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

          Representation of Stellar `#{type.upcase_first}` type.
          """
        EOS
        out.break
        out.puts "@behaviour XDR.Declaration\n\n"
      end

      def render_define_block(out)
        out.puts "defmodule #{@namespace} do"
        out.indent do
          render_moduledoc(out)
        end
        yield
      ensure
        out.puts "end"
        out.break
      end

      def render_define_block_enum_type(out, module_name)
        out.puts "defmodule #{@namespace}.#{module_name.upcase_first} do"
        out.indent do
          render_moduledoc_enum_type(out, module_name)
        end
        yield
      ensure
        out.puts "end"
        out.break
      end

      def render_typedef(out, typedef)
        out.puts "define_type(\"#{name typedef}\", #{build_type_args typedef.declaration.type})"
      end

      def render_const(out, const)
        out.puts "define_type(\"#{const_name const}\", Const, #{const.value});"
      end

      def render_struct(out, struct)
        out.puts "define_type(\"#{name struct}\", Struct,"
        out.indent do
          struct.members.each_with_index do |m, i|
            out.puts "#{member_name m}: #{type_reference m.type}#{comma_unless_last(i, struct.members)}"
          end
        end
        out.puts ")"
      end

      def render_enum(enum)
        file_name = "#{enum.name.underscore.downcase}.ex"
        out = @output.open(file_name)

        render_define_block_enum_type(out, enum.name) do 
          out.indent do
            out.puts "@declarations [\n"
            out.indent do
              enum.members.each_with_index do |m, i|
                out.puts "#{m.name}: #{m.value}#{comma_unless_last(i, enum.members)}"
              end
            end
            out.puts "]\n\n"

            out.puts "@enum_spec %XDR.Enum{declarations: @declarations, identifier: nil}\n\n"

            out.puts "@type t :: %__MODULE__{identifier: atom()}\n\n"

            out.puts "defstruct [:identifier]\n\n"

            out.puts "@spec new(type :: atom()) :: t()\n"
            out.puts "def new(type \\\\ :#{enum.members.first.name}), do: %__MODULE__{identifier: type}\n\n"

            out.puts "@impl true"
            out.puts "def encode_xdr(%__MODULE__{identifier: type}) do\n"
            out.indent do
              out.puts "@declarations\n"
              out.puts "|> XDR.Enum.new(type)\n"
              out.puts "|> XDR.Enum.encode_xdr()\n"
            end
            out.puts "end\n\n"

            out.puts "@impl true"
            out.puts "def encode_xdr!(%__MODULE__{identifier: type}) do\n"
            out.indent do
              out.puts "@declarations\n"
              out.puts "|> XDR.Enum.new(type)\n"
              out.puts "|> XDR.Enum.encode_xdr!()\n"
            end
            out.puts "end\n\n"

            out.puts "@impl true"
            out.puts "def decode_xdr(bytes, spec \\\\ @enum_spec)\n\n"

            out.puts "def decode_xdr(bytes, spec) do\n"
            out.indent do
              out.puts "case XDR.Enum.decode_xdr(bytes, spec) do\n"
              out.indent do
                out.puts "{:ok, {%XDR.Enum{identifier: type}, rest}} -> {:ok, {new(type), rest}}\n"
                out.puts "error -> error\n"
              end
              out.puts "end\n"
            end
            out.puts "end\n\n"

            out.puts "@impl true"
            out.puts "def decode_xdr!(bytes, spec \\\\ @enum_spec)\n\n"

            out.puts "def decode_xdr!(bytes, spec) do\n"
            out.indent do
              out.puts "{%XDR.Enum{identifier: type}, rest} = XDR.Enum.decode_xdr!(bytes, spec)\n"
              out.puts "{new(type), rest}\n"
            end
            out.puts "end\n"
          end
        end
      end

      def render_union(out, union)
        file_name = "#{union.name.underscore.downcase}.ex"
        out = @output.open(file_name)

        render_define_block_enum_type(out, union.name) do 
          out.indent do
            out.puts "alias #{@namespace}.{\n"
            out.indent do
              out.puts "#{type_reference union.discriminant.type},"
              union.normal_arms.each_with_index do |arm, i|
                arm_name = arm.void? ? "Void" : "#{type_reference arm.type}"

                arm.cases.each do |acase|
                  out.puts "#{arm_name}#{comma_unless_last(i, union.normal_arms)}"
                end
              end
            end
            out.puts "}\n\n"

            out.puts "@arms ["
            out.indent do
              union.normal_arms.each_with_index do |arm, i|
                arm_name = arm.void? ? "Void" : "#{type_reference arm.type}"

                arm.cases.each do |acase|
                  switch = if acase.value.is_a?(AST::Identifier)
                    "#{member_name(acase.value)}"
                  else
                    acase.value.text_value
                  end

                  out.puts "#{switch}: #{arm_name}#{comma_unless_last(i, union.normal_arms)}"
                end
              end
            end
            out.puts "]\n\n"

            out.puts "@type value ::"
            out.indent(4) do
              union.normal_arms.each_with_index do |arm, i|
                next if arm.void?
                if i == 0
                  out.puts "#{type_reference arm.type}.t()"
                else
                  out.puts "| #{type_reference arm.type}.t()"
                end
              end
            end
            out.puts "\n"

            out.puts "@type t :: %__MODULE__{value: value(), type: #{type_reference union.discriminant.type}.t()}\n\n"

            out.puts "defstruct [:value, :type]\n\n"

            out.puts "@spec new(value :: value(), type :: #{type_reference union.discriminant.type}.t()) :: t()\n"
            out.puts "def new(value, %#{type_reference union.discriminant.type}{} = type), do: %__MODULE__{value: value, type: type}\n\n"

            out.puts "@impl true"
            out.puts "def encode_xdr(%__MODULE__{value: value, type: type}) do\n"
            out.indent do
              out.puts "type\n"
              out.puts "|> XDR.Union.new(@arms, value)\n"
              out.puts "|> XDR.Union.encode_xdr()\n"
            end
            out.puts "end\n\n"

            out.puts "@impl true"
            out.puts "def encode_xdr!(%__MODULE__{value: value, type: type}) do\n"
            out.indent do
              out.puts "type\n"
              out.puts "|> XDR.Union.new(@arms, value)\n"
              out.puts "|> XDR.Union.encode_xdr!()\n"
            end
            out.puts "end\n\n"

            out.puts "@impl true"
            out.puts "def decode_xdr(bytes, spec \\\\ union_spec())\n\n"

            out.puts "def decode_xdr(bytes, spec) do\n"
            out.indent do
              out.puts "case XDR.Union.decode_xdr(bytes, spec) do\n"
              out.indent do
                out.puts "{:ok, {{type, value}, rest}} -> {:ok, {new(value, type), rest}}\n"
                out.puts "error -> error\n"
              end
              out.puts "end\n"
            end
            out.puts "end\n\n"

            out.puts "@impl true"
            out.puts "def decode_xdr!(bytes, spec \\\\ union_spec())\n\n"

            out.puts "def decode_xdr!(bytes, spec) do\n"
            out.indent do
              out.puts "{{type, value}, rest} = XDR.Union.decode_xdr!(bytes, spec)\n"
              out.puts "{new(value, type), rest}\n"
            end
            out.puts "end\n\n"

            out.puts "@spec union_spec() :: XDR.Union.t()"
            out.puts "defp union_spec do"
            out.indent do
              out.puts "nil\n"
              out.puts "|> #{type_reference union.discriminant.type}.new()\n"
              out.puts "|> XDR.Union.new(@arms)\n"
            end
            out.puts "end\n"
          end
        end
      end

      private
      def name(named)
        return nil unless named.respond_to?(:name)

        parent = name named.parent_defn if named.is_a?(AST::Concerns::NestedDefinition)

        # NOTE: classify will strip plurality, so we restore it if necessary
        plural = named.name.underscore.downcase.pluralize == named.name.underscore.downcase
        base   = named.name.underscore.classify
        result = plural ? base.pluralize : base

        "#{parent}#{result}"
      end

      def const_name(named)
        named.name.underscore.upcase
      end

      def member_name(member)
        name(member).underscore.upcase
      end

      # this can be a string to reference a custom type
      # or a build_type call like build_type(VariableOpaque, 100)
      # args for build_type can be created with build_type_args
      def type_reference(type)
        build_args = build_type_args(type)

        build_args === "#{name type}" ? build_args : "build_type(#{build_args})"
      end

      def comma_unless_last(index, collection)
        if index + 1 >= collection.length
          ""
        else
          ","
        end
      end

      # the args to supply build_type (or define_type(name, ...args))
      def build_type_args(type)
        base_ref = case type
          when AST::Typespecs::Bool
            "Bool"
          when AST::Typespecs::Double
            "Double"
          when AST::Typespecs::Float
            "Float"
          when AST::Typespecs::Hyper
            "HyperInt"
          when AST::Typespecs::Int
            "Int"
          when AST::Typespecs::Opaque
            if type.fixed?
              "Opaque, #{type.size}"
            else
              type.size ? "VariableOpaque, #{type.size}" : "VariableOpaque"
            end
          when AST::Typespecs::Quadruple
            raise "no quadruple support in elixir"
          when AST::Typespecs::String
            "XDR.Type.String, #{type.size}"
          when AST::Typespecs::UnsignedHyper
            "UnsignedHyperInt"
          when AST::Typespecs::UnsignedInt
            "UnsignedInt"
          when AST::Typespecs::Simple
            "#{name type}"
          when AST::Definitions::Base
            "#{name type}"
          when AST::Concerns::NestedDefinition
            "#{name type}"
          else
            raise "Unknown reference type: #{type.class.name}, #{type.class.ancestors}"
        end

        base_type = base_ref === "#{name type}" ? base_ref : "buid_type(base_ref)"

        case type.sub_type
          when :simple
            base_ref
          when :optional
            "Optional, #{base_type}"
          when :array
            is_named, size = type.array_size
            size = is_named ? "\"#{size}\"" : size
            "Array, length: #{size}, type: #{base_type}"
          when :var_array
            is_named, size = type.array_size
            size = is_named ? "\"#{size}\"" : (size || MAX_INT)
            "VariableArray, max_length: #{size}, type: #{base_type}"
          else
            raise "Unknown sub_type: #{type.sub_type}"
        end
      end
    end
  end
end
