// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;

import java.io.IOException;

public final class Constants {
  private Constants() {}
  public static final int FOO = 1244;
  public static final int BAR = FOO;
}
