// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;

import java.io.IOException;

import static MyXDR.Constants.*;
import org.stellar.sdk.Base64Factory;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.Objects;

/**
 * Int3's original definition in the XDR file is:
 * <pre>
 * typedef unsigned int    int3;
 * </pre>
 */
public class Int3 implements XdrElement {
  private XdrUnsignedInteger int3;

  public Int3() {}

  public Int3(XdrUnsignedInteger int3) {
    this.int3 = int3;
  }

  public XdrUnsignedInteger getInt3() {
    return this.int3;
  }

  public void setInt3(XdrUnsignedInteger value) {
    this.int3 = value;
  }

  public static void encode(XdrDataOutputStream stream, Int3  encodedInt3) throws IOException {
    encodedInt3.int3.encode(stream);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
  public static Int3 decode(XdrDataInputStream stream) throws IOException {
    Int3 decodedInt3 = new Int3();
    decodedInt3.int3 = XdrUnsignedInteger.decode(stream);
    return decodedInt3;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.int3);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Int3)) {
      return false;
    }

    Int3 other = (Int3) object;
    return Objects.equals(this.int3, other.int3);
  }
  @Override
  public String toXdrBase64() throws IOException {
    return Base64Factory.getInstance().encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static Int3 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static Int3 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
