// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;

import java.io.IOException;

import static MyXDR.Constants.*;
import java.util.Base64;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.Objects;

// === xdr source ============================================================

//  typedef unsigned hyper  int4;

//  ===========================================================================
public class Int4 implements XdrElement {
  private XdrUnsignedHyperInteger int4;

  public Int4() {}

  public Int4(XdrUnsignedHyperInteger int4) {
    this.int4 = int4;
  }

  public XdrUnsignedHyperInteger getInt4() {
    return this.int4;
  }

  public void setInt4(XdrUnsignedHyperInteger value) {
    this.int4 = value;
  }

  public static void encode(XdrDataOutputStream stream, Int4  encodedInt4) throws IOException {
    encodedInt4.int4.encode(stream);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
  public static Int4 decode(XdrDataInputStream stream) throws IOException {
    Int4 decodedInt4 = new Int4();
    decodedInt4.int4 = XdrUnsignedHyperInteger.decode(stream);
    return decodedInt4;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.int4);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Int4)) {
      return false;
    }

    Int4 other = (Int4) object;
    return Objects.equals(this.int4, other.int4);
  }
  @Override
  public String toXdrBase64() throws IOException {
    return Base64.getEncoder().encodeToString(toXdrByteArray());
  }

  @Override
  public byte[] toXdrByteArray() throws IOException {
    ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrDataOutputStream = new XdrDataOutputStream(byteArrayOutputStream);
    encode(xdrDataOutputStream);
    return byteArrayOutputStream.toByteArray();
  }

  public static Int4 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64.getDecoder().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static Int4 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
