// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;

import java.io.IOException;

import org.stellar.sdk.Base64Factory;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Str2's original definition in the XDR file is:
 * <pre>
 * typedef string str2&lt;&gt;;
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Str2 implements XdrElement {
  private XdrString str2;
  public void encode(XdrDataOutputStream stream) throws IOException {
    str2.encode(stream);
  }

  public static Str2 decode(XdrDataInputStream stream) throws IOException {
    Str2 decodedStr2 = new Str2();
    decodedStr2.str2 = XdrString.decode(stream, Integer.MAX_VALUE);
    return decodedStr2;
  }

  public static Str2 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static Str2 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
