// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;


import java.io.IOException;

import java.util.Arrays;

// === xdr source ============================================================

//  typedef opaque uint514<>;

//  ===========================================================================
public class Uint514 implements XdrElement {
  private byte[] uint514;

  public Uint514() {}

  public Uint514(byte[] uint514) {
    this.uint514 = uint514;
  }

  public byte[] getUint514() {
    return this.uint514;
  }

  public void setUint514(byte[] value) {
    this.uint514 = value;
  }

  public static void encode(XdrDataOutputStream stream, Uint514  encodedUint514) throws IOException {
    int uint514size = encodedUint514.uint514.length;
    stream.writeInt(uint514size);
    stream.write(encodedUint514.getUint514(), 0, uint514size);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
  public static Uint514 decode(XdrDataInputStream stream) throws IOException {
    Uint514 decodedUint514 = new Uint514();
    int uint514size = stream.readInt();
    decodedUint514.uint514 = new byte[uint514size];
    stream.read(decodedUint514.uint514, 0, uint514size);
    return decodedUint514;
  }

  @Override
  public int hashCode() {
    return Arrays.hashCode(this.uint514);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Uint514)) {
      return false;
    }

    Uint514 other = (Uint514) object;
    return Arrays.equals(this.uint514, other.uint514);
  }
}
