// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;

import java.io.IOException;

import org.stellar.sdk.Base64Factory;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Uint514's original definition in the XDR file is:
 * <pre>
 * typedef opaque uint514&lt;&gt;;
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Uint514 implements XdrElement {
  private byte[] uint514;
  public void encode(XdrDataOutputStream stream) throws IOException {
    int uint514Size = uint514.length;
    stream.writeInt(uint514Size);
    stream.write(getUint514(), 0, uint514Size);
  }

  public static Uint514 decode(XdrDataInputStream stream) throws IOException {
    Uint514 decodedUint514 = new Uint514();
    int uint514Size = stream.readInt();
    decodedUint514.uint514 = new byte[uint514Size];
    stream.read(decodedUint514.uint514, 0, uint514Size);
    return decodedUint514;
  }

  public static Uint514 fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static Uint514 fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
