defmodule MyXDR.TestArray do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `TestArray` type.
  """

  @behaviour XDR.Declaration

  alias MyXDR.Int

  @length 1

  @array_type Int

  @array_spec %{type: @array_type, length: @length}

  @type t :: %__MODULE__{items: list(Int.t())}

  defstruct [:items]

  @spec new(items :: list(Int.t())) :: t()
  def new(items), do: %__MODULE__{items: items}

  @impl true
  def encode_xdr(%__MODULE__{items: items}) do
    items
    |> XDR.FixedArray.new(@array_type, @length)
    |> XDR.FixedArray.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{items: items}) do
    items
    |> XDR.FixedArray.new(@array_type, @length)
    |> XDR.FixedArray.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ @array_spec)

  def decode_xdr(bytes, spec) do
    case XDR.FixedArray.decode_xdr(bytes, spec) do
      {:ok, {items, rest}} -> {:ok, {new(items), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ @array_spec)

  def decode_xdr!(bytes, spec) do
    {items, rest} = XDR.FixedArray.decode_xdr!(bytes, spec)
    {new(items), rest}
  end
end
