// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;


import java.io.IOException;

import java.util.Arrays;

// === xdr source ============================================================

//  typedef int TestArray[FOO];

//  ===========================================================================
public class TestArray implements XdrElement {
  private Integer[] TestArray;

  public TestArray() {}

  public TestArray(Integer[] TestArray) {
    this.TestArray = TestArray;
  }

  public Integer[] getTestArray() {
    return this.TestArray;
  }

  public void setTestArray(Integer[] value) {
    this.TestArray = value;
  }

  public static void encode(XdrDataOutputStream stream, TestArray  encodedTestArray) throws IOException {
    int TestArraysize = encodedTestArray.getTestArray().length;
    for (int i = 0; i < TestArraysize; i++) {
      stream.writeInt(encodedTestArray.TestArray[i]);
    }
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
  public static TestArray decode(XdrDataInputStream stream) throws IOException {
    TestArray decodedTestArray = new TestArray();
    int TestArraysize = FOO;
    decodedTestArray.TestArray = new Integer[TestArraysize];
    for (int i = 0; i < TestArraysize; i++) {
      decodedTestArray.TestArray[i] = stream.readInt();
    }
    return decodedTestArray;
  }

  @Override
  public int hashCode() {
    return Arrays.hashCode(this.TestArray);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof TestArray)) {
      return false;
    }

    TestArray other = (TestArray) object;
    return Arrays.equals(this.TestArray, other.TestArray);
  }
}
