// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package MyXDR;

import java.io.IOException;

import org.stellar.sdk.Base64Factory;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Arr's original definition in the XDR file is:
 * <pre>
 * typedef int Arr[2];
 * </pre>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Arr implements XdrElement {
  private Integer[] Arr;
  public void encode(XdrDataOutputStream stream) throws IOException {
    int ArrSize = getArr().length;
    for (int i = 0; i < ArrSize; i++) {
      stream.writeInt(Arr[i]);
    }
  }

  public static Arr decode(XdrDataInputStream stream) throws IOException {
    Arr decodedArr = new Arr();
    int ArrSize = 2;
    decodedArr.Arr = new Integer[ArrSize];
    for (int i = 0; i < ArrSize; i++) {
      decodedArr.Arr[i] = stream.readInt();
    }
    return decodedArr;
  }

  public static Arr fromXdrBase64(String xdr) throws IOException {
    byte[] bytes = Base64Factory.getInstance().decode(xdr);
    return fromXdrByteArray(bytes);
  }

  public static Arr fromXdrByteArray(byte[] xdr) throws IOException {
    ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(xdr);
    XdrDataInputStream xdrDataInputStream = new XdrDataInputStream(byteArrayInputStream);
    return decode(xdrDataInputStream);
  }
}
